services:
  db:
    container_name: metapos-mariadb
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
    networks:
      - metapos_network

networks:
  metapos_network:
    driver: bridge
    name: metapos_network
    external: true
